# -*- coding: utf-8 -*-
"""blinkit project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_j_BdIyYKIJkaODg24csLYPmV-POBTnV
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv("/content/blinkit_data.csv")

df.head(5)

df.tail()

df.info()

df.shape

df.columns

df.dtypes

df["Item Fat Content"].unique()

df["Item Fat Content"]=df["Item Fat Content"].replace({"LF":"Low Fat","low fat":"Low Fat","reg":"Regular"
 })

df["Item Fat Content"].unique()

"""Business requirment

"""

#total sales

total_sales=df["Sales"].sum()

#avg_Sale
avg_Sales=df["Sales"].mean()

#item_sold
no_of_item_sold=df['Sales'].count()

#average Rating
average_rating=df["Rating"].mean()

total_sales =df["Sales"].sum()

total_sales

avg_Sales=df["Sales"].mean()

avg_Sales

no_of_item_sold=df['Sales'].count()

no_of_item_sold

average_rating=df["Rating"].mean()

average_rating

"""from these we can see clearly insights

1.TOTAL SALES -  $ 1201681.00

2.AVG SALES  - $141 .00

3.TOTAL ITEM SOLD - 8523 items are sold

4.AVERAGE RATING - ~4.0 rating

charts
"""

#1 lets checks total sales by fat content

sales_by_fat_content = df.groupby('Item Fat Content')['Sales'].sum()

plt.figure(figsize=(6,6))
plt.pie(sales_by_fat_content, labels=sales_by_fat_content.index,
        autopct= '%1.1f%%',
        colors = ['red', 'green'])

plt.title('Total Sales by Item Fat Content')

plt.legend()
plt.show()

"""# Insights

1.total sales by fat content low fat sales are much higher compare to regular because people are health cuation these days .

2.low fat sales content is is approximate- 65%
& regular fat content- 35%

"""

# total sales by item type

df["Item Type"].unique()

Sales_by_item_type=df.groupby('Item Type')['Sales'].sum().sort_values(ascending=False)
plt.figure (figsize =(10,6))
sns.barplot(x=Sales_by_item_type.index,y=Sales_by_item_type.values,palette="rocket")
plt.xticks(rotation=70)
plt.xlabel('item type')
plt.ylabel('total sales')
plt.title("total sales by item type")

plt.tight_layout()

# Fat  content Outlet for Total Sales

grouped=df.groupby(['Outlet Location Type','Item Fat Content'])['Sales'].sum().unstack()
grouped = grouped [['Regular','Low Fat']]
ax=grouped.plot(kind='bar',figsize=(5,5),title='outlet tier by item fat content')
plt .xlabel('outlet Location tier')
plt.ylabel('Total sales')
plt.show

# Sales By Outlet Size

sales_by_size=df.groupby('Outlet Size')['Sales'].sum()
plt.figure(figsize=(5,6))
plt.pie(sales_by_size, labels=sales_by_size.index,autopct='%1.1f%%')
plt.title('outlet size')
plt.tight_layout
plt.show()

# Total_Sales_Year=('Outlet Estashblishment year')['sales].sum()

Sales_by_Year=df.groupby('Outlet Establishment Year')['Sales'].sum()
plt.figure(figsize=(8,5))
plt.plot(Sales_by_Year.index,Sales_by_Year.values,marker='o',linestyle='-')
plt.xlabel('Outlet Establishment Year')
plt.ylabel('Total Sales')
plt.title('Total Sales by Outlet Establishment Year')
plt.show()

"""#Insights

- from the data  we can interprate sales is higher in Low fat Item  in Campare to Regular Item

-
"""