create database HR;
use HR


-- #1. Retrieve the list of employees who have left the company (Attrition = 'Yes'):
SELECT * FROM hr WHERE Attrition ='Yes';


#2 NO.OF employee attrition 
select count(*) from hr where attrition ="yes";



-- #  3)Find the average age of employees in each department.

select Department,AVG(Age) AS AGE 
FROM hr
GROUP BY Department;

# 4)  Identify employees with a JobSatisfaction rating of 4 and above:

SELECT*FROM HR WHERE SatisfactionScore>=4;

-- 5)List all employees working in the "Research & Development" department.
SELECT* FROM HR WHERE Department ="Research & Development";



-- 6)Calculate the total MonthlyIncome generated by employees in each JobRole



SELECT JobRole, SUM(MonthlyIncome) AS total_month_income
FROM hr
GROUP BY JobRole;

-- 7) 6. Find the total number of employees in each AgeGroup. 

SELECT AgeGroup,COUNT(*)AS TOTAL_EMPLOYEE FROM HR
GROUP BY AgeGroup;


-- 8) Determine the maximum TotalWorkingYears of employees in the company.

SELECT max(TotalWorkingYears)AS TOTAL_WORKINN_YRS
FROM HR;

-- 9) Find the department with the highest average EnvironmentSatisfaction rating

SELECT 
    Department, AVG(EnvironmentSatisfaction) AS ENVIRMENT_SATS
FROM
    HR
GROUP BY Department
ORDER BY  ENVIRMENT_SATS DESC 
LIMIT 1;



-- 10) Identify the average YearsAtCompany for employees grouped by their EducationField.

SELECT 
    EducationField, AVG(YearsAtCompany) AS YR_AT_COMP
FROM
    HR
GROUP BY EducationField;

use HR;

-- 11)Calculate the average PercentSalaryHike for employees who work overtime (OverTime = 
-- 'Yes').

select OverTime ,avg( PercentSalaryHike) as percent_salary_hike from hr where OverTime="yes" 
group by OverTime;

-- 12)List the top 10 highest-paid employees based on their MonthlyIncome.


select * from hr 
order by MonthlyIncome desc
limit 10;


-- 13)Find employees who have worked in more than 3 companies (NumCompaniesWorked > 3).

select * from hr where NumCompaniesWorked>3;


-- 14) . Retrieve the names of employees who are in the highest JobLevel and belong to the "Sales" 
-- department.

select Department ,max(JobLevel) as joblevel from hr
where Department='sales'
order by jobLevel;




-- 15.Identify jobrole who received a PercentSalaryHike greater than the company's average.





SELECT JobRole, PercentSalaryHike
FROM hr
WHERE PercentSalaryHike > (SELECT AVG(PercentSalaryHike) FROM hr);


-- 16.List employees with the least DistanceFromHome in each MaritalStatus category


select MaritalStatus , min(DistanceFromHome)  as emp_min_dist from hr
group by MaritalStatus;



-- 17.. Calculate the total TrainingTimesLastYear for employees grouped by AgeGroup.


SELECT 
    AgeGroup, SUM(TrainingTimesLastYear)
FROM
    hr
GROUP BY AgeGroup;


-- 18.Determine the average number of years employees have been in their current role 
-- (YearsInCurrentRole) for each JobRole.


SELECT 
    JobRole, AVG(YearsInCurrentRole) AS AvgYearsInCurrentRole
FROM
    hr
GROUP BY JobRole;



-- 19) Identify employees who have not received a promotion (YearsSinceLastPromotion = 0) in the 
-- last 5 years.



SELECT 
    *
FROM
    hr
WHERE
    YearsSinceLastPromotion = 0
        AND YearsAtCompany >= 5;
        
        
        
    --    19. Find employees who have worked with their current manager (YearsWithCurrManager) for 
-- more than 10 years.

select * from hr where YearsWithCurrManager>10 ;



SELECT JobRole, Department, YearsWithCurrManager , Attrition
FROM hr
WHERE YearsWithCurrManager > 10;



-- 20)List employees with YearsAtCompany greater than the average working years in the 
-- company.



SELECT 
    Department, JobRole, YearsAtCompany
FROM
    hr
WHERE
    YearsAtCompany > (SELECT 
            AVG(TotalWorkingYears)
        FROM
            hr);





-- 21. Identify the JobRole with the highest average MonthlyIncome.


select JobRole,max(MonthlyIncome)as highest_avg_salry from hr
group by JobRole;


-- 22.Retrieve the JobSatisfaction and RelationshipSatisfaction scores of employees whose 
-- EnvironmentSatisfaction is below the average.


select JobSatisfaction,RelationshipSatisfaction,EnvironmentSatisfaction from hr
where EnvironmentSatisfaction < (select avg(EnvironmentSatisfaction) from hr);




-- 23). Find the department where employees have the highest PerformanceRating.

SELECT 
    Department, MAX(PerformanceRating) AS performance_rating
FROM
    hr
GROUP BY Department;



-- 24). List all EducationField categories where employees have a JobInvolvement score of 3 or 
-- higher





SELECT DISTINCT
    EducationField
FROM
    hr
WHERE
    JobInvolvement >= 3;
    
    
    use hr;
  
-- #25. Analyze the average JobSatisfaction of employees who work overtime compared to those 
-- #who do not. 
 
 
 SELECT 
    OverTime,
    AVG(JobSatisfaction) AS JOB_SATISTFY
FROM
    HR
    GROUP BY OverTime;
    
    
   
   
   #26. Find employees who have StockOptionLevel greater than 1 and are in SalarySlab = 'High'. 


SELECT 
    Department StockOptionLevel, IncomeBracket
FROM
    HR
WHERE
    StockOptionLevel > 1
        AND IncomeBracket = 'HIGH';




-- #30. Identify the factors that differentiate employees with a PerformanceRating of 4 from others. 


SELECT 
    PerformanceRating,
    AVG(PerformanceRating) AS AVG_PERFORMANCE_RATING,
    AVG(AGE) AS AVG_AGE,
    AVG(JobSatisfaction) AS AVG_JOBSATISFACTION_SCORE,
    AVG(MonthlyIncome) AS AVG_SALARY,
    AVG(AnnualIncome) AS AVG_INCOME,
    AVG(DistanceFromHome) AS AVG_DISTANCE_WFH,
    AVG(OverTime) AS AVG_OVERRIME_WORK,
    AVG(YearsAtCompany) AS AVG_YR_AT_COMPANY
FROM HR

GROUP BY PerformanceRating
 HAVING PerformanceRating = 4 ;
 
 
 
 
 
 
 
